spring.application.name=autocare

# Oracle Database
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=AUTOCARE
spring.datasource.password=${AUTOCARE_DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/autocare_mongodb

# Server
server.port=8080

# Thymeleaf
spring.thymeleaf.cache=false