-- =========================================================
-- AutoCare Vehicle Service & Maintenance Management System
-- Script 02 - Create Oracle Tables
-- =========================================================

-- ---------------------------------------------------------
-- 1. CUSTOMER TABLE
-- Stores customer personal and contact information
-- ---------------------------------------------------------

CREATE TABLE CUSTOMER (
    customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    first_name VARCHAR2(50) NOT NULL,

    last_name VARCHAR2(50) NOT NULL,

    nic VARCHAR2(20) NOT NULL,

    phone VARCHAR2(15) NOT NULL,

    email VARCHAR2(100),

    address VARCHAR2(200),

    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_customer
        PRIMARY KEY (customer_id),

    CONSTRAINT uq_customer_nic
        UNIQUE (nic),

    CONSTRAINT uq_customer_email
        UNIQUE (email)
);

-- ---------------------------------------------------------
-- 2. VEHICLE TABLE
-- Stores vehicle registration information
-- ---------------------------------------------------------

CREATE TABLE VEHICLE (
    vehicle_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    customer_id NUMBER NOT NULL,

    registration_no VARCHAR2(20) NOT NULL,

    brand VARCHAR2(50) NOT NULL,

    model VARCHAR2(50) NOT NULL,

    manufacture_year NUMBER(4),

    fuel_type VARCHAR2(20),

    current_mileage NUMBER(10),

    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_vehicle
        PRIMARY KEY (vehicle_id),

    CONSTRAINT uq_vehicle_registration
        UNIQUE (registration_no),

    CONSTRAINT fk_vehicle_customer
        FOREIGN KEY (customer_id)
        REFERENCES CUSTOMER(customer_id)
);

-- ---------------------------------------------------------
-- 3. SERVICE_BOOKING TABLE
-- Stores vehicle service booking information
-- ---------------------------------------------------------

CREATE TABLE SERVICE_BOOKING (
    booking_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    vehicle_id NUMBER NOT NULL,

    booking_date DATE DEFAULT SYSDATE,

    service_date DATE NOT NULL,

    service_type VARCHAR2(50) NOT NULL,

    description VARCHAR2(300),

    estimated_cost NUMBER(10,2),

    booking_status VARCHAR2(20) DEFAULT 'Pending',

    CONSTRAINT pk_service_booking
        PRIMARY KEY (booking_id),

    CONSTRAINT fk_booking_vehicle
        FOREIGN KEY (vehicle_id)
        REFERENCES VEHICLE(vehicle_id),

    CONSTRAINT chk_booking_status
        CHECK (
            booking_status IN (
                'Pending',
                'Confirmed',
                'In Progress',
                'Completed',
                'Cancelled'
            )
        ),

    CONSTRAINT chk_estimated_cost
        CHECK (estimated_cost >= 0)
);

-- ---------------------------------------------------------
-- 4. TECHNICIAN TABLE
-- Stores basic service technician information
-- ---------------------------------------------------------

CREATE TABLE TECHNICIAN (
    technician_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    first_name VARCHAR2(50) NOT NULL,

    last_name VARCHAR2(50) NOT NULL,

    phone VARCHAR2(15) NOT NULL,

    email VARCHAR2(100),

    specialization VARCHAR2(100),

    experience_years NUMBER(2) DEFAULT 0,

    status VARCHAR2(20) DEFAULT 'Available',

    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_technician
        PRIMARY KEY (technician_id),

    CONSTRAINT uq_technician_email
        UNIQUE (email),

    CONSTRAINT chk_technician_experience
        CHECK (experience_years >= 0),

    CONSTRAINT chk_technician_status
        CHECK (
            status IN (
                'Available',
                'Assigned',
                'On Leave',
                'Inactive'
            )
        )
);

-- ---------------------------------------------------------
-- 5. SPARE_PART TABLE
-- Stores spare part inventory information
-- ---------------------------------------------------------

CREATE TABLE SPARE_PART (
    part_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    part_name VARCHAR2(100) NOT NULL,

    part_category VARCHAR2(50),

    unit_price NUMBER(10,2) NOT NULL,

    quantity_in_stock NUMBER(10) DEFAULT 0,

    reorder_level NUMBER(10) DEFAULT 5,

    supplier_name VARCHAR2(100),

    created_date DATE DEFAULT SYSDATE,

    CONSTRAINT pk_spare_part
        PRIMARY KEY (part_id),

    CONSTRAINT chk_part_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_part_quantity
        CHECK (quantity_in_stock >= 0),

    CONSTRAINT chk_reorder_level
        CHECK (reorder_level >= 0)
);

-- ---------------------------------------------------------
-- 6. INVOICE TABLE
-- Stores invoice information for completed service bookings
-- ---------------------------------------------------------

CREATE TABLE INVOICE (
    invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    booking_id NUMBER NOT NULL,

    invoice_date DATE DEFAULT SYSDATE,

    service_charge NUMBER(10,2) DEFAULT 0,

    parts_total NUMBER(10,2) DEFAULT 0,

    tax_amount NUMBER(10,2) DEFAULT 0,

    discount NUMBER(10,2) DEFAULT 0,

    total_amount NUMBER(10,2) DEFAULT 0,

    invoice_status VARCHAR2(20) DEFAULT 'Unpaid',

    CONSTRAINT pk_invoice
        PRIMARY KEY (invoice_id),

    CONSTRAINT uq_invoice_booking
        UNIQUE (booking_id),

    CONSTRAINT fk_invoice_booking
        FOREIGN KEY (booking_id)
        REFERENCES SERVICE_BOOKING(booking_id),

    CONSTRAINT chk_service_charge
        CHECK (service_charge >= 0),

    CONSTRAINT chk_parts_total
        CHECK (parts_total >= 0),

    CONSTRAINT chk_tax_amount
        CHECK (tax_amount >= 0),

    CONSTRAINT chk_discount
        CHECK (discount >= 0),

    CONSTRAINT chk_total_amount
        CHECK (total_amount >= 0),

    CONSTRAINT chk_invoice_status
        CHECK (
            invoice_status IN (
                'Unpaid',
                'Partially Paid',
                'Paid',
                'Cancelled'
            )
        )
);

-- ---------------------------------------------------------
-- 7. INVOICE_ITEM TABLE
-- Stores spare parts included in each invoice
-- ---------------------------------------------------------

CREATE TABLE INVOICE_ITEM (
    invoice_item_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    invoice_id NUMBER NOT NULL,

    part_id NUMBER NOT NULL,

    quantity NUMBER(10) NOT NULL,

    unit_price NUMBER(10,2) NOT NULL,

    subtotal NUMBER(10,2) NOT NULL,

    CONSTRAINT pk_invoice_item
        PRIMARY KEY (invoice_item_id),

    CONSTRAINT fk_invoice_item_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES INVOICE(invoice_id),

    CONSTRAINT fk_invoice_item_part
        FOREIGN KEY (part_id)
        REFERENCES SPARE_PART(part_id),

    CONSTRAINT chk_invoice_item_quantity
        CHECK (quantity > 0),

    CONSTRAINT chk_invoice_item_price
        CHECK (unit_price >= 0),

    CONSTRAINT chk_invoice_item_subtotal
        CHECK (subtotal >= 0)
);

-- ---------------------------------------------------------
-- 8. PAYMENT TABLE
-- Stores payments made for invoices
-- ---------------------------------------------------------

CREATE TABLE PAYMENT (
    payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY,

    invoice_id NUMBER NOT NULL,

    payment_date DATE DEFAULT SYSDATE,

    amount NUMBER(10,2) NOT NULL,

    payment_method VARCHAR2(30) NOT NULL,

    payment_status VARCHAR2(20) DEFAULT 'Completed',

    reference_no VARCHAR2(100),

    CONSTRAINT pk_payment
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_invoice
        FOREIGN KEY (invoice_id)
        REFERENCES INVOICE(invoice_id),

    CONSTRAINT chk_payment_amount
        CHECK (amount > 0),

    CONSTRAINT chk_payment_method
        CHECK (
            payment_method IN (
                'Cash',
                'Card',
                'Bank Transfer',
                'Online'
            )
        ),

    CONSTRAINT chk_payment_status
        CHECK (
            payment_status IN (
                'Pending',
                'Completed',
                'Failed',
                'Refunded'
            )
        )
);