-- =========================================================
-- AutoCare Vehicle Service & Maintenance Management System
-- Script 10 - Application Users and Roles
-- =========================================================

CREATE TABLE APP_USER (
    user_id       NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username      VARCHAR2(50) NOT NULL,
    email         VARCHAR2(100) NOT NULL,
    password_hash VARCHAR2(255) NOT NULL,
    role          VARCHAR2(30) NOT NULL,
    enabled       NUMBER(1) DEFAULT 1 NOT NULL,
    created_date  DATE DEFAULT SYSDATE NOT NULL,

    CONSTRAINT pk_app_user
        PRIMARY KEY (user_id),

    CONSTRAINT uq_app_user_username
        UNIQUE (username),

    CONSTRAINT uq_app_user_email
        UNIQUE (email),

    CONSTRAINT chk_app_user_role
        CHECK (
            role IN (
                'ADMIN',
                'SERVICE_ADVISOR',
                'TECHNICIAN',
                'INVENTORY_MANAGER',
                'CASHIER'
            )
        ),

    CONSTRAINT chk_app_user_enabled
        CHECK (enabled IN (0, 1))
);

CREATE INDEX idx_app_user_role
ON APP_USER(role);

COMMIT;

-- =========================================================
-- Verification
-- =========================================================

SELECT
    table_name
FROM user_tables
WHERE table_name = 'APP_USER';

DESC APP_USER;